### ISSUE TITLE
Key error visable

### ISSUE THREAD

**Issue by Gamelauncher** [giefca/ha-samsungtv-qled#1]
Hi, when trying to load the component I get the below error ...

media_player:
  - platform: samsungtv_qled
    name: "Living TV"
    host: 192.168.1.40
    port: 8002
    timeout: 30
    applist: "Plex, Netflix"

```
Oct 17 19:36:55 hassbian hass[15548]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 273, in async_update_ha_state
Oct 17 19:36:55 hassbian hass[15548]:     self._async_write_ha_state()
Oct 17 19:36:55 hassbian hass[15548]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 314, in _async_write_ha_state
Oct 17 19:36:55 hassbian hass[15548]:     attr.update(self.state_attributes or {})
Oct 17 19:36:55 hassbian hass[15548]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py", line 832, in state_attributes
Oct 17 19:36:55 hassbian hass[15548]:     for attr in ATTR_TO_PROPERTY
Oct 17 19:36:55 hassbian hass[15548]:   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py", line 833, in <dictcomp>
Oct 17 19:36:55 hassbian hass[15548]:     if getattr(self, attr) is not None
Oct 17 19:36:55 hassbian hass[15548]:   File "/home/homeassistant/.homeassistant/custom_components/samsungtv_qled/media_player.py", line 305, in source
Oct 17 19:36:55 hassbian hass[15548]:     if self._application.current_app() is None:
Oct 17 19:36:55 hassbian hass[15548]:   File "/home/homeassistant/.homeassistant/custom_components/samsungtv_qled/samsungctl/application.py", line 68, in current_app
Oct 17 19:36:55 hassbian hass[15548]:     if (self.is_visible(app) is True):
Oct 17 19:36:55 hassbian hass[15548]:   File "/home/homeassistant/.homeassistant/custom_components/samsungtv_qled/samsungctl/application.py", line 54, in is_visible
Oct 17 19:36:55 hassbian hass[15548]:     return app_state['visible']
Oct 17 19:36:55 hassbian hass[15548]: KeyError: 'visible'

```

**Comment by giefca** [comment]
Hi, what is the model of your TV?
Be sure to have netflix and plex installed. Next can your try to go to this url when your TV is turned on with the netflix opened and closed and post the answer? Thanks.
[http://YOUR_IP:8001/api/v2/applications/11101200001](http://YOUR_IP:8001/api/v2/applications/11101200001)

**Comment by Gamelauncher** [comment]
I've tried it, when I run it it gives me:

{"id":"11101200001","name":"Netflix","running":true,"version":"8.0.0","visible":false}
{"id":"3201512006963","name":"Plex","running":true,"version":"4.5.1","visible":false}

Output looks good. Even with only 1 app selected it does this. TV is a Q6FN. If I comment out the app check:

media_player line 304 / 305 the component loads and work fine, albeit no app selector :)
            # self._application = self.get_application()
            # if self._application.current_app() is None:

**Comment by Gamelauncher** [comment]
I saw you made an update, it works fine now! Thanks!

**Comment by Toxminn** [comment]
i unfortunately have the same problem ;(

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 286, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 327, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 796, in state_attributes
    for attr in ATTR_TO_PROPERTY
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 797, in <dictcomp>
    if getattr(self, attr) is not None
  File "/config/custom_components/samsungtv_qled/media_player.py", line 305, in source
    if self._application.current_app() is None:
  File "/config/custom_components/samsungtv_qled/samsungctl/application.py", line 52, in current_app
    if (self.is_visible(app) is True):
  File "/config/custom_components/samsungtv_qled/samsungctl/application.py", line 38, in is_visible
    return app_state['visible']
KeyError: 'visible'

under api/v2/applications/11101200001 the following came out

id | "11101200001"
-- | --
name | "Netflix"
running | true
version | "9.0.0"
visible | true
